# -*- coding: utf-8 -*-
"""List_assignment (2).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SNB4uG8JziH76jDv7yHRUOGGQYPV7AnT

#Q1:
sum the numbers in the list.
[2,3,90,89,45,09]

#Variable
"""

a='2,3,09,'

b='45,89,90'

a+b

"""# Q2:
Add the following data in list above.
1. python
2. 5.9
3. follow
4. [math, 20]
5. [English,80]

#List
"""

a='Python'

b='5.9'

c='follw'

a+b+c

class7=['Maths',20,'English',80]

class7[0:2]

class7[2:4]

class7[1]

class7[3]



"""# Q 3:
Remove the last element from the following list.

[hyder,8,badin,67,50]
"""

l1=['Hyder',8,'Badin','67','50']

l1[0:4]

l1.pop(3)

l1.remove('50')

l1

"""#Q 4: 
Remove the Egg string from the list below.

[flour,30,sugar,90,egg,2,salt,100,gold,10]
"""

l1=['flour',30,'sugar',90,'egg',2,'salt',100,'gold',10]

l1.remove('egg')

l1

"""# Q5:
Merge the lists from the following.

list1 = [8,9,0,90,2,100]

list2 = [1,2,3,4,5]
"""

l1=[8,9,0,90,2,100]
l2=[1,2,3,4,5]

l1+l2

"""# Q6:
Make reverse list of following lists.

1. [shaheen,badin,life,19,45]
2. [get,fight,right,light,bright]
3. [make,cake,sake, lake, bake]
4. [30,80,90,08,9.5]
"""

l1=['shaheen','badin','life',19,45]

l2=['get','fight','right','bright']

l3=['make','cake','sake','lake','bake']

l4=['30,80,90,08,9.5']

l1.reverse()

l1

l2.reverse()

l2

l3.reverse()

l3

l4.reverse()

l4

"""# Q7:
Create a nested list. list one will be main list list 2 will be nested list.

list1 = [kite,flight,55,99,66]
list2 = [great,56,pos,light,20]
"""

l1=['kite','flight',55,99,66]

l1

l2=['great',56,'pos','light',20]

l2

l1.append(l2)

l1

l2.pop(2)

"""# Q8:
Extrate the "pos" from nested list.
"""

l1=['great',56,'pos','light',20]

l1.pop(2)

"""#Q9:
Sort the following lists in ascending order:

1. [89,67,76,45,32,47,34,12,21]
2. [r,f,t,g,y,w,c,v,k,q]
"""

l1=[89,67,76,45,32,47,12,21]

l2=['r','f','t','g','y','w','c','v','k','q']

l1.sort()

l1

l2.sort()

l2

"""# Q10:
Sort the Following lists in descending order.

1. [10,5,45,33,9,190,54,34]
2. [acdf,klmn,iops,wklm,npoi]
"""

l1=[10,5,45,33,9,190,54,34]

l2=['acdf','klmn','iops','wklm','npoi']

l1.sort()

l1

l2.sort()

l2

