# -*- coding: utf-8 -*-
"""python2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xYXXK4Az_99WJy-6CNVhiQloEsOyg1vb
"""

print('Hello World ')

"""# Variable"""

a='Python'
a

pak='1947'

pak

"""b = 'Colab'"""

b

a+b

sum='+'
difference='-'
maltiplication ='*'
division = "/"

2+4

9/2

2*9

9-4

"""# Data types

1. Strings
2. Integers
3. Float
4. Booleam 
"""

s="Python"

type(s)

i=123

type(i)

f=96.3

type(f)

#booleam

b1=True
type(b1)

b2=False
type(b2)