# -*- coding: utf-8 -*-
"""python1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zi_qtb7Jk6DG-TE6ZTVV_cXojU06VHjZ
"""

print('Q1: Who developed Python programing language? Ans: Guido van Rossum. ' )

print('Q2: Which type of programing does Python support? Ans: Python supports four main programming paradigms:Imperative, Functional, Procedural and 0bject-oriented.  ')

print('Q3:Is Python case sensitive when dealling with identifiers? Ans: Yes Python is sensitive language, i.e.,it treats uppercase and characters differently.This applies to identifiers too.You must avoid using the same name with different cases while naming identifiers .       ')

print|('Q4: What is the correct extension of Python file? Ans: .Py ')

print('Q5:Is Python code is compiled or interpreted? Ans: Python is an interpreted language, which means the source code of a Python program is converted into bytecode that is then executed by the Python virtual machine. Python is different from major compiled languages, such as C and C++,as Python code is not required to be built and linked like code for these languages.  ')

print('Q6:Name a few blocks of code use to define in Python file? Ans:The following are blocks: a module, a function body, and a class difinition. Each command typed interactively is a block. A script file ( a file given as standard input to the interpreter or specified as a command line argument to the interpreter) is a code block.')

print('Q7: State a character used to give single line comments in Python? Ans:Python offers a pretty simple and straightforwaed way to write a comment. We can write a single-line comment by adding a single # character before any statement or line of code.  ')

print('Q8: Mention function which can help us to find the version of Python that we are currently working on? Ans: Explanation: The function sys. version can help us to find the version of Python that we currently working on. It also contanins information on the build number and compiler used.')

print('Q9:What does pip stand for Python? Ans:Pip is a recuesive acronym that can stand for either "Pip Installs Packages" or "Pip Installs Python". Alternatively, pip stands for "preferred installer program". Python 2.7.9 and later ( on the python2 series), and Python 3.4 and later include pip (pip3 for python 3) by default ')

print('Q10: Mention few built in function in Python? Ans: Python Built-in Functions.* print() function.  * type()function. * input()function. * abs()function.  * pow()function.  * dir()function.  * sorted()function. * max()function. * round()function. * divmod()function. * id()function. * ord()function. * len()function. * sum()function. * help()function.    ')

print('Q11: What is maximum possible length of an identifier in Python ? Ans:An identifier can have a maximum length of 79 characters in Python. Python is one of the most papular programming languages. ')

print('Q12: What are the benefits of using Python? Ans:Top Reasons to Learn Python. * Data science. * Scientific and mathematical comuting. * Web development. * Finance and trading. * System autmation and administration. * Computer graphics. * Basic game development. * security and penetration testing. * Genreal and application-specific scripting. * Mapping and geography ( GIS software) ')