# -*- coding: utf-8 -*-
"""Python6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O2C8m94ylLUzlrT9j9rUOwfLmvn3UlCH

#List

**Data type**
1. String
2. Integers
3. Float
4. Booleam
"""

a = "Hyder"

i = 12

l =[1,2,'Badin',4.5,True ]
l

class8=['English', 'Science', 'Maths']

class8=['English',20,'Maths',30]

list1=[1,2,'Hyder',5,89,9.2,True,'Python']

list1[2]

class8[1]

class8[0:2]

#even index number
'''This is a Comment 
it will not run'''

list1[::2]

list1[0:6:2]

l2=[1,2,3,4,5]
l3=[6,7,8,9,10]

l2+l3

len(list1)

l6=['Flour',10,'cheeni',2,'oil',3]

l6.append('Tea')

l6

l6.append(2)

l6

l7=['Somosay',3,'chatni',1]

l6.append(l7)

l6

l6[-1][0]

l6.extend(l7)

l6

l6.insert(8,'Eggs')

l6

l6.pop()

l6.pop(2)

l6

l6[::-1]

l6.reverse()

l6

l7=[2,1,96,369,785,89,12,7]
l7.sort()

l7

l7.count(7)