# -*- coding: utf-8 -*-
"""Python3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XwQgRPWaRu1kTIYRTMgch4PS0w_rbrMH

# Strings

1. ' ' /" "
2. Itterable
"""

s1="Pakistan"
s1

#Indexing
s1[1]

s1[3]

s1[5]

#Backword
s1[-1]

s1[-2]

#Slicing
s2="Production"
s2

s2[0:3]

s2[0:4]

s2[0:7:2]

#revers
s2[::-1]

s2[0:7:-1]

s2[7:0:-1]

s3="Coffee"

#for length
len(s3)

s4="Pulao"
s4

s4.find('u')

s5= "laptop"
s5

s5.capitalize()

s5.count("p")

s5.upper()

s6="EXCELANT"
s6

s6.lower()

s5.title()



